//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41852")]
        public int BROADCAST_PORT {
            get {
                return ((int)(this["BROADCAST_PORT"]));
            }
            set {
                this["BROADCAST_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41854")]
        public int TCP_PORT {
            get {
                return ((int)(this["TCP_PORT"]));
            }
            set {
                this["TCP_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41856")]
        public int MULTICAST_PORT {
            get {
                return ((int)(this["MULTICAST_PORT"]));
            }
            set {
                this["MULTICAST_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41855")]
        public int SERVER_AUDIO_PORT {
            get {
                return ((int)(this["SERVER_AUDIO_PORT"]));
            }
            set {
                this["SERVER_AUDIO_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1048576")]
        public int MAX_BUFFER_SIZE {
            get {
                return ((int)(this["MAX_BUFFER_SIZE"]));
            }
            set {
                this["MAX_BUFFER_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int BUFFER_SIZE {
            get {
                return ((int)(this["BUFFER_SIZE"]));
            }
            set {
                this["BUFFER_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41666")]
        public int PING_PORT_OUT_SERVER {
            get {
                return ((int)(this["PING_PORT_OUT_SERVER"]));
            }
            set {
                this["PING_PORT_OUT_SERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41667")]
        public int PING_PORT_IN_SERVER {
            get {
                return ((int)(this["PING_PORT_IN_SERVER"]));
            }
            set {
                this["PING_PORT_IN_SERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy.MM.dd-HH.mm.ss")]
        public string TIMESTAMP_FORMAT {
            get {
                return ((string)(this["TIMESTAMP_FORMAT"]));
            }
            set {
                this["TIMESTAMP_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]

        [global::System.Configuration.DefaultSettingValueAttribute("41853")]
        public int SERVER_DETAILS_PORT {
            get {
                return ((int)(this["SERVER_DETAILS_PORT"]));
            }
            set {
                this["SERVER_DETAILS_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyDM9RT71Dz5LikjMlBErbXHZQq3-fEqWLM")]
        public string GOOGLE_TTS_API_KEY {
            get {
                return ((string)(this["GOOGLE_TTS_API_KEY"]));
            }
            set {
                this["GOOGLE_TTS_API_KEY"] = value;
            }
        }
    }
}
